# Uncomment the next line to define a global platform for your project
# platform :ios, '18.2'

target 'Week3_Cocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher'

  # Pods for Week3_Cocoapods

end
